dataset:
  path: data/raw.csv
  test_size: 0.2
  random_state: 42

preprocessing:
  scale: true
  encode: false
  replace_zeros: true
  fill_missing: median   # median | mean

model:
  # choose one: DecisionTreeClassifier or RandomForestClassifier
  type: RandomForestClassifier

  DecisionTreeClassifier:
    criterion: entropy
    max_depth: 8
    min_samples_split: 2

  RandomForestClassifier:
    n_estimators: 200
    max_depth: 10
    min_samples_split: 4
    n_jobs: -1
